### ISSUE TITLE
CI Backlog

### ISSUE THREAD

**Issue by ghost** [sgc-kn/dashboards#4]
Todos from merged PR #3:
- [ ] regularly clean stale preview deployments; maybe on PR close
- [ ] clean our minio/S3 custom github action; make flexible regarding mirror args like --delete and --overwrite

**Comment by pkel** [comment]
#15. I now do one deployment per PR instead of per commit. The latest deployment automatically purges the previous ones for the same PR. I think this is good enough for now. Also no need for additional bikeshedding the minio/S3 action.
